
services:
  
  mssql:
    container_name: mssql
    restart: always
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=MATF12345678rs2
      - ACCEPT_EULA=Y
    volumes:
      - mssql_data:\var\opt\mssql\data

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
  
  discountdb:
    container_name: discountdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDb
    volumes:
      - postgres_data:\var\lib\postgres\data
  
  pgadmin:
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=razvoj.softvera.matf@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    volumes:
      - pgadmin_data:\root\.pgadmin
  
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:\data\db
  
  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"
      
  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionSettings=mongodb://catalogdb:27017"
    depends_on:
      - catalogdb
    ports:
      - "8000:8080"

  ordering.api:
    container_name: ordering.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:OrderingConnectionString=Server=mssql;Database=OrderDb;User Id=sa;Password=MATF12345678rs2;TrustServerCertificate=True;Encrypt=False;"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on:
      - mssql
      - rabbitmq
    ports:
      - "8004:8080"

  basket.api:
    container_name: basket.api
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - "CacheSettings:ConnectionString=basketdb:6379"
        - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
        - "GrpcSettings:DiscountUrl=http://discount.grpc:8080" 
    depends_on:
        - basketdb
        - discount.grpc
        - rabbitmq
    ports:
      - "8001:8080"
  
  discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"
    depends_on:
      - discountdb
    ports:
      - "8002:8080"
  
  discount.grpc:
    container_name: discount.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"
    depends_on:
      - discountdb
    ports:
      - "8003:8080"
        
  
  identityserver:
    container_name: identityserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:IdentityConnectionString=Server=mssql;Database=IdentityDb;User Id=sa;Password=MATF12345678rs2;TrustServerCertificate=true;Encrypt=false;"
    depends_on:
      - mssql
    ports:
      - "4000:8080"