services:
  discountdb:
    image: postgres
  
  pgadmin:
    image: dpage/pgadmin4
    
  catalogdb:
    image: mongo
    
  basketdb:
    image: redis:alpine
  
  basket.api:
    image: basket.api
    build:
      context: .
      dockerfile: Basket/Basket.API/Dockerfile

  catalog.api:
    image: catalog.api
    build:
      context: .
      dockerfile: Catalog/Catalog.API/Dockerfile
      
  discount.api:
    image: discount.api
    build:
      context: .
      dockerfile: Discount/Discount.API/Dockerfile
  
  discount.grpc:
    image: discount.grpc
    build:
      context: .
      dockerfile: Discount/Discount.GRPC/Dockerfile

volumes:
  mongo_data:
  postgres_data:
  pgadmin_data:
   
