services:
  
  rabbitmq:
    image: rabbitmq:3-management-alpine
  
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
  
  discountdb:
    image: postgres
  
  pgadmin:
    image: dpage/pgadmin4
    
  catalogdb:
    image: mongo
    
  basketdb:
    image: redis:alpine
  
  ordering.api:
    image: ordering.api
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile
      
  basket.api:
    image: basket.api
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  catalog.api:
    image: catalog.api
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
      
  discount.api:
    image: discount.api
    build:
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile
  
  discount.grpc:
    image: discount.grpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.GRPC/Dockerfile

  identityserver:
    image: identityserver
    build:
      context: .
      dockerfile: Security/IdentityServer/Dockerfile

volumes:
  mongo_data:
  postgres_data:
  pgadmin_data:
  mssql_data:
   